Repository kubernetes-csi/lib-volume-populator, pull requests merged in 2022-12, with the labels that each got.

#52 Check for in-tree provisioner
  go.mod
  go.sum
  populator-machinery/controller.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/component-helpers/storage/volume/pv_helpers.go
  vendor/modules.txt
Labels: kind/bug, approved, release-note, size/XXL, lgtm, cncf-cla: yes

#57 Emit events when populator starts / finishes
  example/hello-populator/deploy.yaml
  go.mod
  go.sum
  populator-machinery/controller.go
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/types.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  vendor/k8s.io/client-go/tools/record/OWNERS
  vendor/k8s.io/client-go/tools/record/doc.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/tools/record/events_cache.go
  vendor/k8s.io/client-go/tools/record/fake.go
  vendor/k8s.io/client-go/tools/record/util/util.go
  vendor/modules.txt
Labels: kind/feature, approved, release-note, size/XXL, lgtm, cncf-cla: yes

#61 Update dependency go modules for k8s v1.26.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/k8s.io/component-base/metrics/buckets.go
  vendor/k8s.io/component-base/metrics/collector.go
  vendor/k8s.io/component-base/metrics/counter.go
  vendor/k8s.io/component-base/metrics/gauge.go
  vendor/k8s.io/component-base/metrics/histogram.go
  vendor/k8s.io/component-base/metrics/metric.go
  vendor/k8s.io/component-base/metrics/opts.go
  vendor/k8s.io/component-base/metrics/registry.go
  vendor/k8s.io/component-base/metrics/summary.go
  vendor/k8s.io/component-base/metrics/timing_histogram.go
  vendor/k8s.io/component-base/metrics/value.go
  vendor/k8s.io/component-base/metrics/wrappers.go
  vendor/modules.txt
Labels: approved, release-note-none, lgtm, cncf-cla: yes, size/XL
