Repository kubernetes-csi/lib-volume-populator, pull requests merged in 2022-03, with the labels that each got.

#14 lib: correct function name and error condition checks
  populator-machinery/controller.go
Labels: approved, size/M, release-note-none, lgtm, cncf-cla: yes

#17 Add --namespace argument to deploy populator in another namespace
  example/hello-populator/main.go
Labels: kind/feature, approved, release-note, size/XS, lgtm, cncf-cla: yes, ok-to-test

#19 hello-populator: update deploy.yaml to use published v0.1.0 image
  example/hello-populator/README.md
  example/hello-populator/deploy.yaml
Labels: approved, kind/cleanup, size/M, release-note-none, lgtm, cncf-cla: yes, ok-to-test

#20 Use v1beta1 of the VolumePopulator API
  example/hello-populator/deploy.yaml
Labels: kind/feature, approved, release-note, size/XS, lgtm, cncf-cla: yes

#21 Add v1.0 (beta) release notes
  CHANGELOG/CHANGELOG-1.0.md
Labels: approved, release-note-none, lgtm, cncf-cla: yes, size/L, kind/documentation
