Repository kubernetes-csi/lib-volume-populator, pull requests merged in 2024-03, with the labels that each got.

#152 Make cross-namespace support an optin config
  populator-machinery/controller.go
Labels: kind/bug, approved, size/S, release-note-none, lgtm, cncf-cla: yes

#153 Enable Group Dependabot Updates
  .github/dependabot.yaml
Labels: approved, kind/cleanup, size/S, release-note-none, lgtm, cncf-cla: yes

#116 chore: remove refs to deprecated io/ioutil
  populator-machinery/metrics_test.go
Labels: approved, size/XS, release-note-none, lgtm, cncf-cla: yes, ok-to-test
