Repository kubernetes-csi/lib-volume-populator, pull requests merged in 2025-01, with the labels that each got.

#176 Add mutator functions to allow modify the Kubernetes resources used b…
  populator-machinery/controller.go
  populator-machinery/controller_test.go
Labels: kind/feature, approved, release-note, lgtm, cncf-cla: yes, size/L

#187 Update release tools
  release-tools/.github/dependabot.yaml
  release-tools/.github/workflows/codespell.yml
  release-tools/.github/workflows/trivy.yaml
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/generate-patch-release-notes.sh
  release-tools/go-modules-targeted-update.sh
  release-tools/go-modules-update.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
  release-tools/verify-logcheck.sh
Labels: approved, release-note-none, lgtm, cncf-cla: yes, size/XL

#190 Clean up temporary resources when the original PVC gets deleted
  populator-machinery/controller.go
  populator-machinery/controller_test.go
Labels: kind/feature, approved, release-note, lgtm, cncf-cla: yes, size/XL

#195 Clean up provider specfic code, remove provider related logic
  populator-machinery/controller.go
Labels: approved, release-note, kind/cleanup, size/XS, lgtm, cncf-cla: yes

#199 Add sunnylovestiramisu as reviewer
  OWNERS
Labels: approved, size/XS, release-note-none, lgtm, cncf-cla: yes
